### ISSUE TITLE
小白请教一下，基础安装问题

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [netnr/workers#12]
我再Worker 快速编辑中，把这个文件，复制内容复制进去了，访问地址，发现可以反代。

[workers](https://github.com/netnr/workers)/[cors](https://github.com/netnr/workers/tree/main/cors)/[src](https://github.com/netnr/workers/tree/main/cors/src)/index.js

请问这样是否安装完成了，如果没有还需要什么步骤。

**Comment by netnr** [comment]
可以的
命令行发布方式也可以，只是提供了更多功能，比如调试

**Comment by wy16W2pIilK1xgqN** [comment]
多请教一下，我有个老式网络设备，只支持Http下载，用这个工具能代理Https 的静态资源吗？
我自己使用中，用游览器 可以，但用老路由设备不行。
比如需要下载 `https://bbb.com/bbb.txt` ， 
通过自己搭的服务下载 `http://aaaaaa.workers.dev/https://bbb.com/bbb.txt`
游览器可以，但只支持Http 的老设备不行，
请问有解决的办法吗？

**Comment by netnr** [comment]
看 workers 自带的域名是否支持 http，不支持就绑定自己的域名，配置 http 再试

**Comment by wy16W2pIilK1xgqN** [comment]
> 看 workers 自带的域名是否支持 http，不支持就绑定自己的域名，配置 http 再试
只要确定，应用支持就好。
我再去其它方面找找问题。
谢谢你的帮助。
