### ISSUE TITLE
How to use sematext?

### ISSUE THREAD

**Issue by HereOrCode** [netnr/workers#16]
hi,
I applied for sematext and replaced the API in the options, but I don't know how to set sematext.
https://github.com/netnr/workers/blob/3f6431f2dfbf2347514e3838b049b13ae6e89bf7/cors/src/index.js#L18
<img width="1640" alt="CleanShot 2023-01-29 at 12 49 36@2x" src="https://user-images.githubusercontent.com/83153991/215305571-b628fd05-4b68-4251-a5ab-b52c7d1bb815.png">

**Comment by netnr** [comment]
Change the sematextToken to the one corresponding to the application you created. After deployment, when there is access, there will be a log written, which can be viewed in the statistics list
