### ISSUE TITLE
可不可以加入一个身份验证

### ISSUE THREAD

**Issue by 8ty** [netnr/workers#18]
因为反代可能会被netcraft举报从而导致账号被封禁，
像https://www.v2ex.com/t/901304 这个一样，所以想能不能用access(zero trust)来限制访问，或者是
https://developers.cloudflare.com/workers/examples/basic-auth/
添加简单的验证

**Comment by netnr** [comment]
以前是在代码里面做白名单或黑名单限制，但好似会消耗访问次数，后面就去掉了，改为用 Cloudflare WAF 来配置，最优选的方式

**Comment by 8ty** [comment]
> 以前是在代码里面做白名单或黑名单限制，但好似会消耗访问次数，后面就去掉了，改为用 Cloudflare WAF 来配置，最优选的方式

不知道用zero trust 来设置会不会消耗次数

**Comment by netnr** [comment]
![image](https://user-images.githubusercontent.com/10579621/216863878-d72d9dab-5e01-4bf6-8dd6-8eb4157075e0.png)

根据流量顺序，现在 Access 就是 zero trust ，还没到 Workers ，所以应该不消耗，
其实用 WAF 配置白名单、黑名单挺简单的

**Comment by 8ty** [comment]
> ![image](https://user-images.githubusercontent.com/10579621/216863878-d72d9dab-5e01-4bf6-8dd6-8eb4157075e0.png)
> 
> 根据流量顺序，现在 Access 就是 zero trust ，还没到 Workers ，所以应该不消耗， 其实用 WAF 配置白名单、黑名单挺简单的

我想要自己或者身边几个朋友用用，用zero trust 的话就可以精准一点，WAF好像只能按照国家来配置
